### PR TITLE
adds a KeyEncoder type class to encode a custom value as Json key

### PR DESCRIPTION
**Pull request by pjan**
Initial shot at addressing #38 

Not sure about how to do the attribution correctly,
nor as to where (and how) you would like to see it be tested (don't seem to fine a suite that is testing the encoder instances).

Can iterate over this according to feedback/answers.

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks for getting this started, @pjan. I think a note and link in the Scaladoc would work for attribution, since we credit Argonaut in the top-level `NOTICE` file now.

About testing: round-trip tests for encoders come from the `CodecTest` laws, and most of the tests for specific encoders are in `CodecSuites.scala`. This would be a rare case where we don't provide matching decoders (except when the key is `String`), but you could define a custom key type like `case class MyKey(s: String)`, give it a `KeyEncoder` instance, and then write a custom decoder for `Map[MyKey, A: Decoder]` (using a `map` on the ordinary `Map` decoder).

One question: is there a reason to keep the `Map[String, A: Encoder]` instance and this one, instead of providing a `KeyEncoder` instance for strings (which is what Argonaut does)?

**Comment by travisbrown** [comment]
Another thought: we could use `cats.Show` instead of `KeyEncoder`, which lets us avoid including a fairly meaningless type class in our API, and lets users get instances for standard types a little more easily.

**Comment by pjan** [comment]
Great idea on the use of `cats.Show` instead of defining another typeclass.

One question: if I were to remove the Encoder instance for `Map[String, V]` in favour of the more generic instance for `Map[K, V]` where the instance observes an implicit `Show[String]`, where am I to put that implicit so it doesn't require everybody to import it/put it in scope?

**Comment by pjan** [comment]
@travisbrown shot at using `Show` for this. The `SerializableSuite` currently fails as the compiler can't resolve an implicit instance of `Encoder[Map[String, Int]]` in scope, now that there's no concrete instance of it.

At the same time, I'm not really sure whether bringing `Show[String]` implicitly in scope is what I'd want to do.

Thoughts?

**Comment by travisbrown** [comment]
@pjan Sorry about the long delay in review (I've been traveling). I agree that we probably don't want to put a `Show[String]` instance into scope for people, so we could either go back to a custom type class or treat `Map[String, V]` separately. I'll be home tomorrow and will think about this in the meantime—

**Comment by travisbrown** [comment]
These commits were included in #213, which is now merged.

**Pull request closed without merging**
