### PR TITLE
Generic derivation overhaul (with configurability)

### LINKED ISSUE #69: Derivation of big case class
Derivation of big case class finish by a `could not find implicit value for parameter e: io.circe.Encoder[A]`and `could not find implicit value for parameter e: io.circe.Decoder[A]`

[Here a gist that show the problem ](https://gist.github.com/crakjie/92138a2c685fb544cc28)

### PR DESCRIPTION
**Pull request by travisbrown**
Supersedes #163 and #79. Also fixes #69, although I'm not entirely sure why. Still needs tests before it gets merged.

### CODE REVIEW

**Comment by travisbrown** [comment]
The build is failing because of an interaction between macro-compat and sbt-unidoc on 2.10 that I'll investigate later.

**Comment by travisbrown** [comment]
For what it's worth, these changes may speed up compilation a bit (at least they do on my machine, from over a minute for `tests/test:compile` to under 50 seconds).

**Comment by travisbrown** [comment]
Quick update: there's a problem here for e.g. the following nested case classes:

```scala
case class Foo(someField: Int)
case class Foos(foos: List[Foo])
```

In this case if you ask for a snake-case decoder for `Foos` the decoder it uses for each `Foo` won't be configured to use snake case.

I'm working on a fix that switches the inheritance relationship between `Decoder` and `ConfiguredDecoder`, and will update the PR soon.

**Comment by wennergr** [comment]
Any updates on this? Would love to see this PR move forward ;)

**Comment by sveinnfannar** [comment]
Really looking forward to seeing this released :)

**Comment by travisbrown** [comment]
@wennergr @sveinnfannar Unfortunately configurability won't be in 0.4.0, which will be out very soon (possibly today), but 0.4.0 does include an overhaul (see #247) in preparation for configurability that's bringing huge improvements in compile times and stability—see the [0.4.0-RC1 release notes](https://github.com/travisbrown/circe/releases/tag/v0.4.0-RC1), the link [here](https://twitter.com/travisbrown/status/716620394761961473), etc.

I'm hoping to have 0.5 out with configurability in the next couple of weeks, but no promises yet.

**Comment by sveinnfannar** [comment]
Thanks for the update @travisbrown!

**Comment by dvic** [comment]
Any updates on this (in light of the 0.5.x releases)? Will this land in 0.6.x?

By the way, thanks a lot for this awesome library 👍 !

**Comment by travisbrown** [comment]
Superseded (mostly) by #429.

**Pull request closed without merging**
