### PR TITLE
Update versions (with one other small clarification)

### PR DESCRIPTION
**Pull request by travisbrown**

### CODE REVIEW

**Comment by fthomas** [comment]
This build https://travis-ci.org/travisbrown/circe/jobs/86886404 which should use Scala 2.10.6 compiles with 2.11.7. I think you are also hitting https://github.com/scoverage/sbt-scoverage/issues/146

**Comment by vkostyukov** [comment]
:+1:

**Comment by travisbrown** [comment]
@fthomas Oh, ouch! I guess the best thing to do is roll back to 1.2.0 for now?

**Comment by fthomas** [comment]
@travisbrown That is what I did in refined.

**Comment by travisbrown** [comment]
@fthomas Thanks for catching that! I've just pushed a fix.

**Pull request merged**
