### PR TITLE
Move ops-to-path printing into HistoryOp

### PR DESCRIPTION
**Pull request by tobias-johansson**
Ref: #224

### CODE REVIEW

**Comment by tobias-johansson** [comment]
Um, build failure seems unrelated to my changes...?

**Comment by travisbrown** [comment]
Oh, damn—yeah, that's #265, which I reported yesterday, after seeing it once out of a few dozen jobs. I was hoping it wouldn't pop up again so soon. I'll restart the job…

Thanks for doing this! I probably won't be able to review until this afternoon, but will get it in asap.

**Comment by tobias-johansson** [comment]
Hey, no rush

**Comment by travisbrown** [comment]
Thanks, @tobias-johansson! I think we should probably add some tests (now that this is a little more easily testable), but I don't think that should block merging this.

**Pull request merged**
