### PR TITLE
Remove io.circe.auto._ from example in README

### PR DESCRIPTION
**Pull request by groz**
Replaced by import io.circe.generic.auto._

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks, @groz! One thing—do you mind changing the line to `import io.circe.generic.auto._` instead of deleting it, so that this represents a complete REPL session?

**Comment by groz** [comment]
@travisbrown isn't it already imported on the first line?

**Comment by travisbrown** [comment]
@groz The idea is that that whole code section should represent a copy-and-pasted REPL session, so when you see this:

```scala
scala> sealed trait Foo
defined trait Foo
```

The second line is what the REPL prints after you enter everything after the prompt in the first.

The Scala REPL allows you to paste in a complete REPL session like this (it'll ignore the prompts and result lines), so using it in documentation has the advantage of both showing what will happen and being directly copy-and-paste-able.

**Comment by groz** [comment]
Ah, understood. Thanks.

**Comment by travisbrown** [comment]
@groz Thanks again for catching this! Will merge when green.

**Pull request merged**
