### PR TITLE
StateT decoders

### PR DESCRIPTION
**Pull request by travisbrown**
This PR includes a couple of first steps toward the functionality requested by @olafurpg in #374. The goal is to support the construction of decoders that consume fields from JSON objects so that it's possible to have decoding fail if there are leftover fields.

For example:

```scala
import io.circe.Decoder, io.circe.jawn.decode
import cats.instances.either._

case class Foo(a: String, b: Int, c: Boolean)

implicit val decodeFoo: Decoder[Foo] = Decoder.fromState(
  for {
    a <- Decoder.state.decodeField[String]("a")
    b <- Decoder.state.decodeField[Int]("b")
    c <- Decoder.state.decodeField[Boolean]("c")
    _ <- Decoder.state.requireEmpty
  } yield Foo(a, b, c)
)
```

And then:

```scala
scala> import cats.syntax.show._
import cats.syntax.show._

scala> val good = """{ "a": "xyz", "b": 1, "c": false }"""
good: String = { "a": "xyz", "b": 1, "c": false }

scala> val bad = """{ "a": "xyz", "b": 1, "c": false, "d": null, "e": -1 }"""
bad: String = { "a": "xyz", "b": 1, "c": false, "d": null, "e": -1 }

scala> decode[Foo](good)
res9: Either[io.circe.Error,Foo] = Right(Foo(xyz,1,false))

scala> decode[Foo](bad).left.foreach(e => println(e.show))
DecodingFailure at .a{!_/}.b{!_/}.c{!_/}: Leftovers: d, e
res0: Any = ()
```

These methods still need documentation and tests, but I wanted to run the basic API past people. One alternative to the `State` suffixes would be to have a `state` object inside `Decoder` with `read`, `requireEmpty`, etc. methods, so that you could more easily import just these methods when you want to build decoders in this way.

This PR currently depends on #343—once that's merged I'll rebase.

### CODE REVIEW

**Comment by non** [comment]
@travisbrown This design seems OK to me, but I just wanted to propose an alternate way to think about this.

You could imagine taking an existing decoder and updating it with extra assertions that must be true. For example, maybe you read three optional keys but you want exactly two of them to be true (no more no less). Either before or after decoding you could check that the condition is valid, and if it isn't you'd fail the decoding.

Under this model instead of maintaining read state in this way, you'd just look for a key in the object that isn't in your set of allowed keys.

One advantage of this approach is that it makes certain kinds of invariants a bit easier to enforce. On the other hand it's also a bit fiddly. I just wanted to put it out there for you to consider.

**Comment by andyscott** [comment]
Just wanted to mention that I'm very interested in using this. It will be particularly useful if we can get a generic derivation mechanism.

I may be able to lend a hand once a solution is chosen.

**Comment by travisbrown** [comment]
@andyscott What do you think of the current API (setting aside generically derived instances for the moment)? I'd like to include this in 0.6.0, so any feedback would be much appreciated.

**Comment by travisbrown** [comment]
@non Sorry about the long delay in responding, but I agree that that approach (validating the keys or other properties as a separate initial step) works well in many cases—it's what I've been recommending that people do in this situation up until this PR.

This PR isn't a replacement for that approach, but more an alternative for cases where it helps to have something more compositional (the way we currently build up generically derived instances, for example).

**Pull request merged**
