### PR TITLE
Add Scala.js support

### PR DESCRIPTION
**Pull request by alexarchambault**
Fixes https://github.com/travisbrown/circe/issues/12

### CODE REVIEW

**Comment by alexarchambault** [comment]
@InTheNow I didn't see any circe/jfc repo in your repo list, so I allowed myself to take the "Add Scala.js support" cap here :-).

**Comment by alexarchambault** [comment]
The JS tests are horribly slow to run. Don't know if https://github.com/non/cats/pull/432 could address that.

**Comment by InTheNow** [comment]
@alexarchambault  YES!!! YES!!! My mission is accomplished!!!!

**Comment by alexarchambault** [comment]
:-D

**Comment by InTheNow** [comment]
Re the tests - do you mean on Travis-CI or in general? I ask as right now Travis-CI is just really slow, I believe due to bintray and S3, etc. An unfortunate time to make build changes

**Comment by alexarchambault** [comment]
@InTheNow they're quite slow locally for me

**Comment by InTheNow** [comment]
@alexarchambault OK - now it's safe to do so, I'll clone and have a quick look :wink:

**Comment by alexarchambault** [comment]
About this PR, note that there's no parser for Scala.js yet. (I may have submitted this PR too early.)

As @ngbinh [suggested](https://github.com/travisbrown/circe/issues/12#issuecomment-127269537), the parser from upickle could be a good basis for that.

**Comment by alexarchambault** [comment]
2.11 builds fail because of lack of memory it seems (I'd attribute the `EOFException`s to that).

2.10 because of lack of cats snapshots for it (which themselves don't get published for lack of memory, on the cats side this time).

**Comment by InTheNow** [comment]
I'm sorting out the cats build now - Travis-CI looks healthier now

**Comment by lihaoyi** [comment]
If you want a fast-ish common JSON parser, upickle used to have one

- https://github.com/lihaoyi/upickle-pprint/blob/10d8a8a278ef697e4c23106f0772da59806d82fb/shared/main/scala/upickle/Js.scala

I only later swapped to using Jawn on the server and JSON.parse on the client for a 5-10x speedup;

**Comment by InTheNow** [comment]
> 2.10 because of lack of cats snapshots

Cats travis builds are fine, publishing is not happening due to authentication issues.

If you still have build issues, let me know I can perhaps point you in the right direction. For now:

- See the [js](https://github.com/non/cats/blob/master/tests/js/src/test/scala/cats/tests/Platform.scala) and [jvm](https://github.com/non/cats/blob/master/tests/jvm/src/test/scala/cats/tests/Platform.scala) platform overrides used  in [CatsSuite](https://github.com/non/cats/blob/master/tests/shared/src/test/scala/cats/tests/CatsSuite.scala#L20)
- see the [jvm options file](https://github.com/non/cats/blob/master/.jvmopts)
- In the [cats .travis.yml](https://github.com/non/cats/blob/master/.travis.yml) I split the build into multiple calls to sbt to stop memory blowing up.

**Comment by travisbrown** [comment]
Okay, now that we have a cats snapshot with Scala.js support, I'm going to go ahead and merge this when it's green (I've just restarted the build), and then follow up with a PR that adds a condition to the Travis config that checks `$TRAVIS_BRANCH` and only runs `validateJS` for a new `scalajs` branch (similar to what @alexarchambault suggests in #12).

**Comment by travisbrown** [comment]
Oh, no!—there aren't actually cats 1.3 snapshots for 2.10 (I only tried 2.11 locally). Will check on this now.

**Comment by travisbrown** [comment]
Oh, nevermind—it looks like it's just an issue with us still having a `cats-std` dependency. I'm trying the build locally without it.

**Comment by travisbrown** [comment]
Thanks @alexarchambault! I'm in an airport security line at the moment but feel free to push master to the `scalajs` branch.

**Pull request merged**
