### PR TITLE
Add documentation from https://github.com/travisbrown/circe/releases

### PR DESCRIPTION
**Pull request by bthuillier**
In this PR I mostly paste documentation from [releases page] (https://github.com/travisbrown/circe/releases), it's a first step to have all the documentation centralized.

### CODE REVIEW

**Comment by bthuillier** [comment]
ping @travisbrown

**Comment by travisbrown** [comment]
Thanks, @bthuillier, and sorry for the delay—I was trying to decide whether to go ahead and use some of this material to start a tut site, but I think that can wait for now. I'll wrap this up today.

**Comment by bthuillier** [comment]
@travisbrown I think that you forgot about the PR, if you want some help to continu this work for building a tut site I'll be happy to help

**Comment by travisbrown** [comment]
@bthuillier No, just really busy. 😦

There are two changes I think we should make here (I can do them in a follow-up PR):

1. Some explanation of _when_ you'd want to use semi-automatic derivation and why.
2. This is nitpicky, but for the sake of consistency let's use standard punctuation, etc. (e.g. periods at the end of sentences, colons to introduce code).

**Comment by bthuillier** [comment]
I can do that, it doesn't bother me

**Comment by bthuillier** [comment]
@travisbrown If you have the detailed description about semi-automatic derivation ( the only one I have in mind it's related to compilation time )

**Comment by travisbrown** [comment]
Thanks, @bthuillier! I'm going to go ahead and merge this, and will fill in some details about motivation as soon as possible.

**Pull request merged**
